### ISSUE TITLE
parser answers with 500 Internal Server error

### ISSUE THREAD

**Issue by sebix** [Lichtbit/regexpad#16]
When choosing a testing tool  != javascript, the server-side parser is called to validate the regex. But `http://regexpad.com/parser/parser.php` answers with a `500 (Internal Server Error)`. I tested it with both Firefox 37.0.1 and Chromium 41.0.

**Comment by georf** [comment]
This is fixed. With the commit of the bug #15 it changed the htaccess file for the new apache version.

**Comment by sebix** [comment]
I assumed that this coincided with the fix of that issue, but couldn't imagine how it would affect the parser. Thanks for the quick fix again.
